# Generated by Django 3.2.9 on 2021-12-08 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Имя пользователя', 'verbose_name_plural': 'Имена пользователей'},
        ),
    ]
