# Generated by Django 3.2.9 on 2022-01-19 18:11

from django.db import migrations, models
import django.db.models.deletion
import scrapping.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name City')),
                ('slug', models.CharField(blank=True, max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Name City',
                'verbose_name_plural': 'Name City',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Язык программирования')),
                ('slug', models.TextField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Name Language',
                'verbose_name_plural': 'Names Language',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='Вакансия')),
                ('company', models.CharField(max_length=250)),
                ('description', models.TextField(verbose_name='Описание')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapping.language', verbose_name='language')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapping.city', verbose_name='city')),
            ],
            options={
                'verbose_name': 'Name Vacancy',
                'verbose_name_plural': 'Names Vacancy',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_data', models.JSONField(default=scrapping.models.defaults_url)),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapping.language', verbose_name='language')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapping.city', verbose_name='city')),
            ],
            options={
                'unique_together': {('city', 'Language')},
            },
        ),
    ]
