# Generated by Django 3.2.9 on 2021-12-08 05:44

from django.db import migrations, models
import django.db.models.deletion
import scrapping.models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_data', models.JSONField(default=scrapping.models.defaults_url)),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapping.language', verbose_name='language')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapping.city', verbose_name='city')),
            ],
            options={
                'unique_together': {('city', 'Language')},
            },
        ),
    ]
