# Generated by Django 3.2.9 on 2021-12-08 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0002_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Name Vacancy', 'verbose_name_plural': 'Names Vacancy'},
        ),
    ]
