# Generated by Django 3.2.9 on 2021-11-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0002_auto_20211127_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Name Language', 'verbose_name_plural': 'Names Language'},
        ),
        migrations.AddField(
            model_name='language',
            name='slug',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
