# Generated by Django 3.2.9 on 2021-11-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0003_auto_20211127_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='Вакансия')),
                ('company', models.CharField(max_length=250)),
                ('description', models.TextField(verbose_name='Описание')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapping.language', verbose_name='language')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapping.city', verbose_name='city')),
            ],
            options={
                'verbose_name': 'Name Language',
                'verbose_name_plural': 'Names Language',
            },
        ),
    ]
