# Generated by Django 3.2.9 on 2021-11-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0004_vacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Name Vacancy', 'verbose_name_plural': 'Names Vacancy'},
        ),
    ]
